name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      SH_VERSION_SUFFIX: preview

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          include-prerelease: true

      - name: Install .NET Framework 4.6.2 reference assemblies
        run: nuget install Microsoft.NETFramework.ReferenceAssemblies.net462 -Version 1.0.0 -OutputDirectory ./.nuget/packages

      - name: Set up environment variables
        run: |
          echo "MSBuildFrameworkPathOverride=$(pwd)/.nuget/packages/Microsoft.NETFramework.ReferenceAssemblies.net462/1.0.0/lib/net462" >> $GITHUB_ENV
          echo "MSBuildSDKsPath=$(pwd)/.nuget/packages/Microsoft.NETFramework.ReferenceAssemblies.net462/1.0.0/build/native" >> $GITHUB_ENV

      - name: Install coverlet.msbuild
        run: dotnet add src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj package coverlet.msbuild --version 3.1.0

      - name: Restore NuGet packages
        run: dotnet restore src/SignhostAPIClient.sln

      - name: Build solution
        run: dotnet build src/SignhostAPIClient.sln

      - name: Pack NuGet package
        run: dotnet pack src/SignhostAPIClient/SignhostAPIClient.csproj --output ./artifacts

      - name: Run tests with coverage
        run: dotnet test --no-build src/SignhostAPIClient.Tests/SignhostAPIClient.Tests.csproj --collect:"XPlat Code Coverage" --settings coverlet.runsettings
        env:
          APPVEYOR_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

      - name: Notify on Gitter
        if: ${{ always() }}
        run: curl -X POST -d "message=Build succeeded" https://webhooks.gitter.im/e/69c5136a745342743ec4
